name: miccai2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.7.9
  - readline=8.0
  - setuptools=50.3.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tmux=3.1
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.10.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - alembic==1.4.3
    - antspyx==0.3.8
    - argon2-cffi==20.1.0
    - asgiref==3.2.10
    - async-generator==1.10
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==20.2.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cachetools==4.1.1
    - cffi==1.14.3
    - chardet==3.0.4
    - charset-normalizer==2.1.1
    - chart-studio==1.1.0
    - cliff==3.4.0
    - cmaes==0.7.0
    - cmd2==1.3.11
    - colorama==0.4.4
    - colorlog==4.4.0
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - django==3.1.2
    - einops==0.6.0
    - entrypoints==0.3
    - filelock==3.9.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - future==0.18.2
    - gevent==20.9.0
    - google-auth==1.22.1
    - google-auth-oauthlib==0.4.1
    - greenlet==0.4.17
    - grpcio==1.33.1
    - huggingface-hub==0.12.0
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==6.0.0
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==1.2.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.2
    - kiwisolver==1.2.0
    - lightning-utilities==0.6.0.post0
    - lxml==4.9.2
    - mako==1.1.3
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.2
    - mistune==0.8.4
    - monai==1.1.0
    - multidict==6.0.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.2
    - networkx==2.5
    - nibabel==3.2.0
    - nilearn==0.10.0
    - notebook==6.1.4
    - numpy==1.19.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.1.0
    - optuna==2.2.0
    - packaging==23.0
    - pandas==1.3.5
    - pandocfilters==1.4.3
    - parso==0.7.1
    - patsy==0.5.1
    - pbr==5.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.1
    - plotly==4.12.0
    - prettytable==0.7.2
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.8
    - protobuf==3.13.0
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.7.2
    - pyparsing==2.4.7
    - pyperclip==1.8.1
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - pytorch-lightning==1.9.0
    - pytz==2020.1
    - pywavelets==1.1.1
    - pyyaml==6.0
    - pyzmq==19.0.2
    - qtconsole==4.7.7
    - qtpy==1.9.0
    - requests==2.28.2
    - requests-oauthlib==1.3.0
    - retrying==1.3.3
    - rsa==4.6
    - scikit-image==0.17.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.0
    - send2trash==1.5.0
    - six==1.15.0
    - sklearn==0.0
    - sqlalchemy==1.3.20
    - sqlparse==0.4.1
    - statsmodels==0.12.0
    - stevedore==3.2.2
    - tensorboard==2.4.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.7.0
    - terminado==0.9.1
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tifffile==2020.10.1
    - timm==0.6.12
    - torch==1.13.1
    - torch-tb-profiler==0.4.1
    - torchmetrics==0.11.1
    - torchvision==0.7.0
    - tornado==6.0.4
    - tqdm==4.64.1
    - traitlets==5.0.5
    - typing-extensions==4.4.0
    - urllib3==1.25.11
    - wcwidth==0.2.5
    - webcolors==1.11.1
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - yarl==1.8.2
    - zipp==3.4.0
    - zope-event==4.5.0
    - zope-interface==5.1.2

