#!/bin/bash

#SBATCH --job-name=test         # Assign a descriptive job name
#SBATCH -N 1                    # Request 1 node
#SBATCH --mem=50G              # Request memory
#SBATCH -t 20:30:00             # Set maximum time
#SBATCH --partition=tier2_gpu   # Partition selection
#SBATCH --account=aristeidis_sotiras
#SBATCH --exclude=gpu02

#SBATCH --output=slurm-%A_%a.out
#SBATCH --error=slurm-%A_%a.err

source /home/l.peiwang/miniconda3/etc/profile.d/conda.sh
# Move into the directory you want to inspect
export PYTHONNOUSERSITE=1

conda activate pasta_env_new_2025
# Upgrade pip so you're sure to get the newest wheels

conda update pip

pip install scikit-learn

# Install antspyx from PyPI
import torch
print(torch.backends.cudnn.enabled)         # True if cuDNN is enabled
print(torch.backends.cudnn.version())       # e.g. 8500
print(torch.backends.cudnn.is_available())  # True if PyTorch sees cuDNN


#python train.py

