#!/bin/bash


#SBATCH --job-name=test #Assign a descriptive job name

#SBATCH -N 1                    # Request 1 node
#SBATCH --mem=40G               # Request 400GB memory
#SBATCH -t 10:30:00             # Set maximum time


##SBATCH --gres=gpu:1

#SBATCH --gres=gpu:1
#SBATCH --partition=tier2_gpu
#SBATCH --account=aristeidis_sotiras
#SBATCH --exclude=gpu02


##SBATCH --array=0-7              # Array of 8 tasks (0 to 7)

# Output and error filenames based on job ID and task ID
#SBATCH --output=output4.out
#SBATCH --error=output4.err


# Activate Conda
source /home/l.peiwang/miniconda3/etc/profile.d/conda.sh


conda activate miccai2
pip install openpyxl



module load cuda
module load cudnn

#python train.py
python train_new.py --finetune --ckpt_path logs/aagn/version_23/checkpoints/aagn.ckpt
#python  train.py
#python inference.py
