name: preprocess
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - ld_impl_linux-64
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.7.9
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - antspyx==0.3.8
    - astor==0.8.1
    - charset-normalizer==3.1.0
    - chart-studio==1.1.0
    - cycler==0.11.0
    - deepbrain==0.1
    - fonttools==4.38.0
    - gast==0.5.3
    - grpcio==1.51.3
    - h5py==3.8.0
    - idna==3.4
    - imageio==2.26.0
    - importlib-metadata==6.0.0
    - joblib==1.2.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - markdown==3.4.1
    - markupsafe==2.1.2
    - matplotlib==3.5.3
    - mock==5.0.1
    - networkx==2.6.3
    - nibabel==4.0.2
    - numpy==1.21.6
    - packaging==23.0
    - pandas==1.3.5
    - patsy==0.5.3
    - pillow==9.4.0
    - plotly==5.13.1
    - protobuf==3.20.3
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - requests==2.28.2
    - retrying==1.3.4
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - six==1.16.0
    - statsmodels==0.13.5
    - tenacity==8.2.2
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tqdm==4.65.0
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - webcolors==1.12
    - werkzeug==2.2.3
    - zipp==3.15.0

